# Generated by Django 5.1.5 on 2025-03-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0001_initial'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationvirtualmachine',
            name='installedapplication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_virtual_machines', to='adestis_netbox_applications.installedapplication'),
        ),
        migrations.AlterField(
            model_name='applicationvirtualmachine',
            name='virtual_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_virtual_machines', to='virtualization.virtualmachine'),
        ),
    ]
