# Generated by Django 5.1.8 on 2025-04-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationClusterGroup',
        ),
    ]
