# Generated by Django 5.1.8 on 2025-05-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterassignment',
            name='application_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='clustergroupassignment',
            name='application_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_group_assignments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='application_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='virtualmachineassignment',
            name='application_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machine_assignments', to='contenttypes.contenttype'),
        ),
    ]
