# Generated by Django 5.0.10 on 2025-02-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
