# Generated by Django 5.1.5 on 2025-03-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0001_initial'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationClusterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_cluster_groups', to='virtualization.clustergroup')),
                ('installedapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_cluster_groups', to='adestis_netbox_applications.installedapplication')),
            ],
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='cluster_group',
            field=models.ManyToManyField(through='adestis_netbox_applications.ApplicationClusterGroup', to='virtualization.clustergroup'),
        ),
    ]
