# Generated by Django 5.1.8 on 2025-04-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0002_delete_applicationclustergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installedapplication',
            name='cluster',
        ),
        migrations.DeleteModel(
            name='ApplicationCluster',
        ),
    ]
