# Generated by Django 5.1.5 on 2025-03-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0002_alter_applicationvirtualmachine_installedapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installedapplication',
            name='cluster_group',
        ),
        migrations.DeleteModel(
            name='ApplicationClusterGroup',
        ),
    ]
