# Generated by Django 5.1.8 on 2025-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0003_remove_installedapplication_cluster_and_more'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapplication',
            name='cluster',
            field=models.ManyToManyField(to='virtualization.cluster'),
        ),
    ]
