# Generated by Django 5.1.5 on 2025-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0005_rename_tenant_groups_installedapplication_tenant_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapplication',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
