# Generated by Django 5.1.8 on 2025-06-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0006_remove_installedapplication_manufacturer_and_more'),
        ('dcim', '0200_populate_mac_addresses'),
        ('tenancy', '0017_natural_ordering'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterassignment',
            old_name='installed_application',
            new_name='installedapplication',
        ),
        migrations.RenameField(
            model_name='clustergroupassignment',
            old_name='installed_application',
            new_name='installedapplication',
        ),
        migrations.RenameField(
            model_name='virtualmachineassignment',
            old_name='installed_application',
            new_name='installedapplication',
        ),
        migrations.RemoveField(
            model_name='deviceassignment',
            name='installed_application',
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='installedapplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='adestis_netbox_applications.installedapplication'),
        ),
        migrations.AlterField(
            model_name='installedapplication',
            name='cluster',
            field=models.ManyToManyField(blank=True, related_name='installedapplication', through='adestis_netbox_applications.ClusterAssignment', to='virtualization.cluster'),
        ),
        migrations.AlterField(
            model_name='installedapplication',
            name='cluster_group',
            field=models.ManyToManyField(blank=True, related_name='installedapplication', through='adestis_netbox_applications.ClusterGroupAssignment', to='virtualization.clustergroup'),
        ),
        migrations.AlterField(
            model_name='installedapplication',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='installedapplication', through='adestis_netbox_applications.DeviceAssignment', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='installedapplication',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_tenant', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='installedapplication',
            name='tenant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_tenant_group', to='tenancy.tenantgroup'),
        ),
        migrations.AlterField(
            model_name='installedapplication',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='installedapplication', through='adestis_netbox_applications.VirtualMachineAssignment', to='virtualization.virtualmachine'),
        ),
    ]
