# Generated by Django 5.1.8 on 2025-06-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0007_rename_installed_application_clusterassignment_installedapplication_and_more'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installedapplication',
            options={'ordering': ('contact',)},
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logincredentials_contact', to='tenancy.contact'),
        ),
    ]
