# Generated by Django 5.2.5 on 2026-05-05 10:37

import django.db.models.deletion

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0016_alter_installedapplication_application_types_and_more'),
        ('extras', '0123_journalentry_kind_default'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapplication',
            name='approval_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='approval_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installedapplication_contact_group', to='tenancy.contactgroup'),
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='parent_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of_installedapplication', to='adestis_netbox_applications.installedapplication'),
        ),
        migrations.AddField(
            model_name='software',
            name='approval_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='software',
            name='approval_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='software_contact', to='tenancy.contact'),
        ),
        migrations.AddField(
            model_name='software',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_contact_group', to='tenancy.contactgroup'),
        ),
        migrations.AddField(
            model_name='software',
            name='parent_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of_software', to='adestis_netbox_applications.software'),
        ),
        migrations.RemoveField(
            model_name='installedapplication',
            name='contact',
        ),
        migrations.AlterField(
            model_name='installedapplication',
            name='version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=150)),
                ('approval_status', models.CharField(max_length=50, null=True)),
                ('approval_info', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('version', models.CharField(blank=True, max_length=150)),
                ('installedapplication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_application', to='adestis_netbox_applications.installedapplication')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_software', to='adestis_netbox_applications.software')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Software Version',
                'verbose_name_plural': 'Software Versions',
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='software_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_software_version', to='adestis_netbox_applications.softwareversion'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_software_version', to='adestis_netbox_applications.softwareversion'),
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='installedapplication_contact', to='tenancy.contact'),
        ),
    ]
