# Generated by Django 5.2.5 on 2026-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0017_installedapplication_approval_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapplication',
            name='approval_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='approval_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='approval_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
