# Generated by Django 5.1.8 on 2026-05-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0017_installedapplication_approval_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapplication',
            name='application_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='adestis_netbox_applications.installedapplicationtypes'),
        ),
    ]
