# Generated by Django 5.2.5 on 2026-04-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0018_alter_installedapplication_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareversion',
            name='url',
        ),
    ]
