# Generated by Django 5.1.8 on 2026-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0018_alter_installedapplication_application_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='software_version',
        ),
        migrations.RemoveField(
            model_name='softwareversion',
            name='installedapplication',
        ),
    ]
