# Generated by Django 5.1.8 on 2026-05-11 12:55

import adestis_netbox_applications.models.software
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0019_remove_software_software_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapplication',
            name='url',
            field=adestis_netbox_applications.models.software.RFCURLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='software',
            name='url',
            field=adestis_netbox_applications.models.software.RFCURLField(max_length=300),
        ),
    ]
