# Generated by Django 5.2.5 on 2026-04-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0019_remove_softwareversion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapplication',
            name='software_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_software_version', to='adestis_netbox_applications.softwareversion'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_software_version', to='adestis_netbox_applications.softwareversion'),
        ),
    ]
