# Generated by Django 5.2.5 on 2026-04-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0020_installedapplication_software_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareversion',
            name='installedapplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_application', to='adestis_netbox_applications.installedapplication'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_software', to='adestis_netbox_applications.software'),
        ),
    ]
