# Generated by Django 5.1.8 on 2026-05-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0020_alter_installedapplication_url_alter_software_url'),
        ('dcim', '0200_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_manufacturer', to='dcim.manufacturer'),
        ),
    ]
