# Generated by Django 5.2.5 on 2026-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0021_softwareversion_installedapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapplication',
            name='version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='version',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
