# Generated by Django 5.1.8 on 2026-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0021_alter_software_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapplication',
            name='software_versions',
            field=models.ManyToManyField(blank=True, related_name='assigned_applications', to='adestis_netbox_applications.softwareversion'),
        ),
    ]
