# Generated by Django 5.2.5 on 2026-05-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0022_alter_installedapplication_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareversion',
            name='installedapplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_application', to='adestis_netbox_applications.installedapplication'),
        ),
    ]
