# Generated by Django 5.1.8 on 2026-05-19 11:39

import adestis_netbox_applications.models.software
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0022_installedapplication_software_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='url',
            field=adestis_netbox_applications.models.software.RFCURLField(blank=True, max_length=300),
        ),
    ]
