name: "local_docker_netbox_account_management_plugin"
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "a.nabiyev@adestis.de"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
    - "13001:80"

  netbox: &netbox
    image: adestis-netbox-plugin-account-management-plugin:latest
    user: root
    build:
      context: ../
      dockerfile: Dev-Dockerfile
    depends_on:
    - postgres
    - redis
    - redis-cache
    ports:
      - "13000:8080"
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_EMAIL: "admin@adestis.de"
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "admin"
      DEVELOPER: "True"
      DEBUG: "True"
      DB_WAIT_DEBUG: "1"
      
    # docker-compose run netbox sh -c "python manage.py makemigrations adestis_netbox_applications"
    # docker-compose run netbox sh -c "cat /opt/netbox/base_requirements.txt" > ../docs/base_requirements.txt
    # docker-compose run netbox sh -c "cat /opt/netbox/base_requirements.txt" > ../docs/requirements-container.txt
    # docker-compose run netbox sh -c "cat /opt/netbox/base_requirements.txt" > ../docs/requirements.txt
    volumes:
     - ./../adestis_netbox_applications/migrations:/opt/netbox/venv/lib/python3.12/site-packages/adestis_netbox_applications/migrations:rw
     - ./../adestis_netbox_applications/static:/opt/netbox/venv/lib/python3.12/site-packages/adestis_netbox_applications/static:rw
  netbox-worker:
    image: adestis-netbox-plugin-account-management-plugin:latest
    build:
      context: ../
      dockerfile: Dev-Dockerfile
  # netbox-housekeeping:
  #   <<: *netbox
